spring.application.name=batchpractice
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/springbatchpracticepr
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Spring Batch Configuration
spring.batch.job.enabled=false
spring.batch.initialize-schema=always
spring.batch.jdbc.initialize-schema=always

# Logging
logging.level.org.springframework.batch=DEBUG
logging.level.com.example.batchdemo=DEBUG
logging.level.org.hibernate.SQL=DEBUG